image: python:latest

stages:
  - backup-internal
  - backup-external
  - publish

envidat:
  stage: backup-internal
  before_script:
    - pip install pdm
    - pdm install
    - echo "$CONFIG_INI" > config_ci.ini
    - scp config_ci.ini "$CI_PROJECT_DIR/config.ini"
  script:
     - pdm run websnap-cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT" --early_exit

ods:
  stage: backup-external
  before_script:
    - pip install pdm
    - pdm install
    - echo $CONFIG_ODS_INI > config_ci_ods.ini
    - scp config_ci_ods.ini "$CI_PROJECT_DIR/config_ods.ini"
  script:
    pdm run websnap-cli --s3_uploader --config config_ods.ini --early_exit



publish-package:
  stage: publish
  image: python:3.11-slim-bookworm
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm
  script:
    - pdm config repository.pypi.username "__token__"
    - pdm config repository.pypi.password "${PYPI_API_TOKEN}"
    - pdm publish
