image: python:3.13-slim-bookworm

stages:
  - test
  - backup
  - opendata-swiss
  - nasa
  - publish

variables:
  ENDPOINT_URL: $ENDPOINT_URL
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

test:
  stage: test
  before_script:
    - pip install pdm
    - pdm sync --dev
    - apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*
    - echo "$TEST_CONFIG_JSON" > config_test.json
    - scp config_test.json "$CI_PROJECT_DIR/tests/config_test.json"
  script:
    - pdm run pytest --cov=websnap --cov-report=term --no-cov-on-fail --s3-config "$CI_PROJECT_DIR/tests/config_test.json"
  coverage: '/TOTAL.*\s+(\d+)%/'

test-tox:
  stage: test
  image: python:${PYTHON_VERSION}-slim-bookworm
  before_script:
    - pip install pdm
    - pdm sync --dev
    - apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*
    - echo "$TEST_CONFIG_JSON" > config_test.json
    - scp config_test.json "$CI_PROJECT_DIR/tests/config_test.json"
  script:
    - pdm run tox -e py${PYTHON_VERSION}  # Run tox for different versions
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.11", "3.12", "3.13" ]
  when: manual

backup:
  stage: backup
  before_script:
    - pip install pdm
    - pdm sync
    - apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*
    - echo "$CONFIG_INI" > config_ci.ini
    - scp config_ci.ini "$CI_PROJECT_DIR/config.ini"
  script:
     - pdm run websnap-cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT" --early_exit

opendata-swiss:
  stage: opendata-swiss
  before_script:
    - pip install pdm
    - pdm sync
    - apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*
    - echo "$CONFIG_OPENDATA_SWISS_INI" > config_ci_opendata_swiss.ini
    - scp config_ci_opendata_swiss.ini "$CI_PROJECT_DIR/config_opendata_swiss.ini"
  script:
     - pdm run websnap-cli --s3_uploader --config config_opendata_swiss.ini --backup_s3_count "$BACKUP_S3_COUNT" --early_exit

nasa:
  stage: nasa
  before_script:
    - pip install pdm
    - pdm sync
    - apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*
    - echo $CONFIG_NASA_JSON > config_ci_nasa.json
    - scp config_ci_nasa.json "$CI_PROJECT_DIR/config_nasa.json"
    - |
      if [ "$NASA_EARLY_EXIT" == "true" ]; then
        export EXIT="--early_exit"  
      else
        export EXIT=""         
      fi
  script:
    pdm run websnap-cli --s3_uploader --config config_nasa.json --section_config "$SECTION_CONFIG_NASA_JSON" $EXIT
  allow_failure: true

publish-package:
  stage: publish
  image: python:3.11-slim-bookworm
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm
  script:
    - pdm config repository.pypi.username "__token__"
    - pdm config repository.pypi.password "${PYPI_API_TOKEN}"
    - pdm publish
