image: python:latest

stages:
  - test
  - backup
  - nasa
  - publish


test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  before_script:
    - pip install pdm
    - pdm install --dev
  script:
    - pdm run pytest --cov=websnap --cov-report=xml
  artifacts:
    paths:
      - coverage.xml
  coverage: "/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/"

backup:
  stage: backup
  before_script:
    - pip install pdm
    - pdm install
    - echo "$CONFIG_INI" > config_ci.ini
    - scp config_ci.ini "$CI_PROJECT_DIR/config.ini"
  script:
     - pdm run websnap-cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT" --early_exit

nasa:
  stage: nasa
  before_script:
    - pip install pdm
    - pdm install
    - echo $CONFIG_NASA_JSON > config_ci_nasa.json
    - scp config_ci_nasa.json "$CI_PROJECT_DIR/config_nasa.json"
  script:
    pdm run websnap-cli --s3_uploader --config config_nasa.json --section_config "$SECTION_CONFIG_NASA_JSON" --early_exit

publish-package:
  stage: publish
  image: python:3.11-slim-bookworm
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm
  script:
    - pdm config repository.pypi.username "__token__"
    - pdm config repository.pypi.password "${PYPI_API_TOKEN}"
    - pdm publish
