image: python:latest

stages:
  - deploy

before_script:
  - pip install -r requirements.txt

deploy:
  stage: deploy
  before_script:
    - echo "$CONFIG_INI" > config.ini
    - scp config.ini "$CI_PROJECT_DIR/src/websnap/config/config.ini"
  script:
    - python -m src.websnap.websnap_cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT"