image: python:latest

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - pip install pdm
    - pdm install
    - echo "$CONFIG_INI" > config_templates.ini
    - scp config_templates.ini "$CI_PROJECT_DIR/config.ini"
  script:
     - websnap_cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT" --early_exit