image: python:latest

stages:
  - pip-package
  - deploy

pip-package:
  stage: pip-package
  rules:
    - if: $CI_COMMIT_TAG
  image: python:3.11
  before_script:
    - pip install pdm
  script:
    - pdm config repository.pypi.username "__token__"
    - pdm config repository.pypi.password "${PYPI_API_TOKEN}"
    - pdm publish


deploy:
  stage: deploy
  before_script:
    - pip install pdm
    - pdm install
    - echo "$CONFIG_INI" > config_ci.ini
    - scp config_ci.ini "$CI_PROJECT_DIR/config.ini"
  script:
     - pdm run websnap-cli --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT" --early_exit