image: python:latest

stages:
  - deploy

variables:
  CONFIG_PATH: "$CI_PROJECT_DIR/config/$CONFIG_INI"

before_script:
  - pip install pdm
  - pdm install

deploy:
  stage: deploy
  script:
    - pdm run websnap-cli --config $CONFIG_PATH --s3_uploader --backup_s3_count "$BACKUP_S3_COUNT"