[project]
name = "websnap"
version = "4.0.0"
description = "Copies files retrieved from an API to an S3 bucket or a local machine."
authors = [
    {name = "Rebecca Buchholz"},
]
maintainers = [
    {name = "EnviDat", email="envidat@wsl.ch"}
]
dependencies = [
    "pydantic>=2.13.2",
    "boto3>=1.42.91",
    "requests>=2.33.1",
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Topic :: Internet",
    "Topic :: System",
    "Topic :: System :: Archiving",
    "Topic :: System :: Archiving :: Backup",
    "Topic :: System :: Archiving :: Mirroring",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators"
]
readme = "README.md"
license = {text = "MIT"}
keywords = [
    "S3",
    "Boto3",
    "boto3",
    "API",
    "backup",
    "AWS",
    "AWS SDK",
    "AWS SDK for Python"
]

[project.urls]
documentation = "https://github.com/EnviDat/websnap/blob/main/README.md"
repository = "https://github.com/EnviDat/websnap"
changelog = "https://github.com/EnviDat/websnap/blob/main/CHANGELOG.md"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
websnap-cli = "websnap.websnap_cli:main"

[tool.pdm.scripts]
websnap-cli = {call = "websnap.websnap_cli:main"}

[tool.coverage.run]
omit = [
    "*/tests/*"
]


[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "tox>=4.53.0",
    "tox-pdm>=0.7.2",
    "ruff>=0.15.11",
    "pytest-cov>=7.1.0",
]
